;; Selected packages
(setq my-packages (list 'ack
                        'ag
                        'anzu
                        'col-highlight
                        'company
                        'chruby
                        'clojure-mode
                        'goto-chg
                        'go-mode
                        'jinja2-mode
                        'flycheck
                        'flymake-ruby
                        'git
                        'grizzl
                        'inf-ruby
                        'jsx-mode
                        'levenshtein
                        'multiple-cursors
                        'nyan-mode
                        'project
                        'projectile
                        'projectile-rails
                        'rainbow-mode
                        'robe
                        'rspec-mode
                        'ruby-tools
                        'ruby-block
                        'ruby-additional
                        'ruby-hash-syntax
                        'ruby-refactor
                        'rust-mode
                        'rvm
                        'smartscan
                        'solarized-theme
                        'better-defaults
                        'toml-mode
                        'use-package
                        'virtualenvwrapper
                        'wakatime-mode
                        'yaml-mode
                        'zenburn-theme))
